kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim-on-gluster-subvol
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster-subvol"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
