apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: "gcr.io/google_containers/nginx-slim:0.8"
    name: nginx-pod
    ports:
    - containerPort: 80
      name: web
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-on-gluster-subvol
  volumes:
  - name: nginx-on-gluster-subvol
    persistentVolumeClaim:
      claimName: nginx-claim-on-gluster-subvol

